#ifndef CAE_PERFORMANCE_DATA_MONITORING_TOOL_DATAMANAGER_H
#define CAE_PERFORMANCE_DATA_MONITORING_TOOL_DATAMANAGER_H

#endif //CAE_PERFORMANCE_DATA_MONITORING_TOOL_DATAMANAGER_H

class DataManager {
public:
    void addThreadInfo(json threadInfo);
};